### ISSUE TITLE
[Suggestion] Let's apply the same formatting as MLIR?

### ISSUE THREAD

**Issue by nicolasvasilache** [andidr/teckyl#5]
In MLIR we use `git-clang-format --style=LLVM HEAD^`.
I'll send a PR using those configurations to see how it looks like.
Historically the TC format has been much less thought out.

**Comment by andidr** [comment]
ACK for the coherence with MLIR / LLVM. Thanks for pointing this out. I will close the issue as soon as the PR is merged.

**Comment by nicolasvasilache** [comment]
Addressed in #7 .
